### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by kergoth** [anfederico/Amazon-Alert#3]
Getting this when attempting the intial setup: `urllib2.HTTPError: HTTP Error 400: Bad Request`. Any tips on how to diagnose?

**Comment by kergoth** [comment]
After adding some exception handling, and going to the url manually, I see:
```
Your AccessKey Id is not registered for Product Advertising API. Please use the AccessKey Id obtained after registering at https://affiliate-program.amazon.com/gp/flex/advertising/api/sign-in.html.
```

So clearly the aws credentials require the product advertising API, which is what I asked in the other issue and was basically ignored. I'd suggest documenting this requirement.

**Comment by kergoth** [comment]
Update: new failure: `Your AccessKeyId is not authorized to perform this operation. Please check IAM policies for the Access Key.`

**Comment by kergoth** [comment]
Looks like since the Product Advertising API isn't fully supported by IAM, you need to either use the root credentials or attach the AdministratorAccess policy. I'd recommend documenting this requirement, as the project can't be used with any arbitrary aws access key, but only with this policy.

**Comment by anfederico** [comment]
Ok, I will update the documentation.
